### ISSUE TITLE
Error on catching exception on async function

### ISSUE THREAD

**Issue by Ricardonacif** [simlu/lambda-rollbar#141]
Hey @simlu, thanks for this package! I was testing the following scenario when it showed up as a success execution but hided an exception (which I could spot on the logs). The axios post call should raise an error. See below:
```js
const rollbar = require('lambda-rollbar')({
  accessToken: "REMOVED",
  environment: process.env.ENVIRONMENT,
  enabled: true,
  template: 'aws-sls-lambda-proxy'
});


module.exports.CallbackToSoniaBackend = rollbar.wrap(async event => {
  const axios = require('axios')
  const params = {
    test: true
  }
  console.log("Callback to backend params", params)
  const response = await axios.post('https://localhost:3012', params)
  console.log("response:", response.data)
  return event
})
```
This executed "successfully" according to the lambda dashboard, but you can spot on the logs the following:

```
018-08-20T22:45:38.891Z f2a7381f-fb1a-49fa-837e-e00f6c3a08d8  (node:1) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
at JSON.stringify (<anonymous>)
at module.exports.e (/var/task/node_modules/lambda-rollbar/lib/util/ensure-string.js:1:141)
at submitToRollbar (/var/task/node_modules/lambda-rollbar/lib/rollbar.js:23:41)
at Object.error (/var/task/node_modules/lambda-rollbar/lib/rollbar.js:62:54)
at handler.then.catch.err (/var/task/node_modules/lambda-rollbar/lib/rollbar.js:67:14)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)

2018-08-20T22:45:38.891Z  f2a7381f-fb1a-49fa-837e-e00f6c3a08d8  (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```
am I getting something wrong here?

**Comment by simlu** [comment]
Oh... found the error. You are returning from the function. This is very bad practice and eslint would have caught that. We are using [js-gardener](https://github.com/simlu/js-gardener) for testing.

**Comment by simlu** [comment]
Just released a [new version](https://github.com/simlu/lambda-rollbar/releases) that should fix your specific issue. Please let us know!

**Comment by Ricardonacif** [comment]
Will give it a try and update here! Thanks!

**Comment by Ricardonacif** [comment]
Awesome! Indeed it was fixed! Thanks for the help 👍

**Comment by simlu** [comment]
No worries! Let me know if you have any further questions!

You might also want to take a look at lambda-tdd btw. It's a test framework that allows you to test your lambda functions locally. We use it to test all our functions!

**Comment by Ricardonacif** [comment]
That's a great tip! We soon will have to write tests for lambda stuff. THanks agane!
